<?php
/**
 * ACF field group registration for Sustainable Food System Events.
 * Loaded by sustainable-food-system-events.php
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Register ACF field group for the Sustainable Food System Event CPT.
 */
function sfse_register_acf_fields() {

    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    // ── Country choices (ISO 3166-1 alpha-2) ──────────────────────────────────
    $country_choices = array(
        // Europe
        'AD' => 'AD - Andorra',
        'AL' => 'AL - Albania',
        'AT' => 'AT - Austria',
        'BA' => 'BA - Bosnia and Herzegovina',
        'BE' => 'BE - Belgium',
        'BG' => 'BG - Bulgaria',
        'BY' => 'BY - Belarus',
        'CH' => 'CH - Switzerland',
        'CY' => 'CY - Cyprus',
        'CZ' => 'CZ - Czech Republic',
        'DE' => 'DE - Germany',
        'DK' => 'DK - Denmark',
        'EE' => 'EE - Estonia',
        'ES' => 'ES - Spain',
        'FI' => 'FI - Finland',
        'FR' => 'FR - France',
        'GB' => 'GB - United Kingdom',
        'GR' => 'GR - Greece',
        'HR' => 'HR - Croatia',
        'HU' => 'HU - Hungary',
        'IE' => 'IE - Ireland',
        'IS' => 'IS - Iceland',
        'IT' => 'IT - Italy',
        'LI' => 'LI - Liechtenstein',
        'LT' => 'LT - Lithuania',
        'LU' => 'LU - Luxembourg',
        'LV' => 'LV - Latvia',
        'MC' => 'MC - Monaco',
        'MD' => 'MD - Moldova',
        'ME' => 'ME - Montenegro',
        'MK' => 'MK - North Macedonia',
        'MT' => 'MT - Malta',
        'NL' => 'NL - Netherlands',
        'NO' => 'NO - Norway',
        'PL' => 'PL - Poland',
        'PT' => 'PT - Portugal',
        'RO' => 'RO - Romania',
        'RS' => 'RS - Serbia',
        'RU' => 'RU - Russia',
        'SE' => 'SE - Sweden',
        'SI' => 'SI - Slovenia',
        'SK' => 'SK - Slovakia',
        'SM' => 'SM - San Marino',
        'TR' => 'TR - Turkey',
        'UA' => 'UA - Ukraine',
        'VA' => 'VA - Vatican City',
        'XK' => 'XK - Kosovo',

        // North America
        'AG' => 'AG - Antigua and Barbuda',
        'BB' => 'BB - Barbados',
        'BL' => 'BL - Saint Barthélemy',
        'BM' => 'BM - Bermuda',
        'BS' => 'BS - Bahamas',
        'BZ' => 'BZ - Belize',
        'CA' => 'CA - Canada',
        'CR' => 'CR - Costa Rica',
        'CU' => 'CU - Cuba',
        'DM' => 'DM - Dominica',
        'DO' => 'DO - Dominican Republic',
        'GD' => 'GD - Grenada',
        'GT' => 'GT - Guatemala',
        'HN' => 'HN - Honduras',
        'HT' => 'HT - Haiti',
        'JM' => 'JM - Jamaica',
        'KN' => 'KN - Saint Kitts and Nevis',
        'LC' => 'LC - Saint Lucia',
        'MQ' => 'MQ - Martinique',
        'MX' => 'MX - Mexico',
        'NI' => 'NI - Nicaragua',
        'PA' => 'PA - Panama',
        'PR' => 'PR - Puerto Rico',
        'SV' => 'SV - El Salvador',
        'TT' => 'TT - Trinidad and Tobago',
        'US' => 'US - United States',
        'VC' => 'VC - Saint Vincent and the Grenadines',

        // South America
        'AR' => 'AR - Argentina',
        'BO' => 'BO - Bolivia',
        'BR' => 'BR - Brazil',
        'CL' => 'CL - Chile',
        'CO' => 'CO - Colombia',
        'EC' => 'EC - Ecuador',
        'FK' => 'FK - Falkland Islands',
        'GF' => 'GF - French Guiana',
        'GY' => 'GY - Guyana',
        'PE' => 'PE - Peru',
        'PY' => 'PY - Paraguay',
        'SR' => 'SR - Suriname',
        'UY' => 'UY - Uruguay',
        'VE' => 'VE - Venezuela',

        // Asia
        'AE' => 'AE - United Arab Emirates',
        'AF' => 'AF - Afghanistan',
        'AM' => 'AM - Armenia',
        'AZ' => 'AZ - Azerbaijan',
        'BD' => 'BD - Bangladesh',
        'BH' => 'BH - Bahrain',
        'BN' => 'BN - Brunei',
        'BT' => 'BT - Bhutan',
        'CN' => 'CN - China',
        'GE' => 'GE - Georgia',
        'HK' => 'HK - Hong Kong',
        'ID' => 'ID - Indonesia',
        'IL' => 'IL - Israel',
        'IN' => 'IN - India',
        'IQ' => 'IQ - Iraq',
        'IR' => 'IR - Iran',
        'JO' => 'JO - Jordan',
        'JP' => 'JP - Japan',
        'KG' => 'KG - Kyrgyzstan',
        'KH' => 'KH - Cambodia',
        'KP' => 'KP - North Korea',
        'KR' => 'KR - South Korea',
        'KW' => 'KW - Kuwait',
        'KZ' => 'KZ - Kazakhstan',
        'LA' => 'LA - Laos',
        'LB' => 'LB - Lebanon',
        'LK' => 'LK - Sri Lanka',
        'MM' => 'MM - Myanmar',
        'MN' => 'MN - Mongolia',
        'MO' => 'MO - Macao',
        'MV' => 'MV - Maldives',
        'MY' => 'MY - Malaysia',
        'NP' => 'NP - Nepal',
        'OM' => 'OM - Oman',
        'PH' => 'PH - Philippines',
        'PK' => 'PK - Pakistan',
        'PS' => 'PS - Palestine',
        'QA' => 'QA - Qatar',
        'SA' => 'SA - Saudi Arabia',
        'SG' => 'SG - Singapore',
        'SY' => 'SY - Syria',
        'TH' => 'TH - Thailand',
        'TJ' => 'TJ - Tajikistan',
        'TL' => 'TL - Timor-Leste',
        'TM' => 'TM - Turkmenistan',
        'TW' => 'TW - Taiwan',
        'UZ' => 'UZ - Uzbekistan',
        'VN' => 'VN - Vietnam',
        'YE' => 'YE - Yemen',

        // Africa
        'AO' => 'AO - Angola',
        'BF' => 'BF - Burkina Faso',
        'BI' => 'BI - Burundi',
        'BJ' => 'BJ - Benin',
        'BW' => 'BW - Botswana',
        'CD' => 'CD - DR Congo',
        'CF' => 'CF - Central African Republic',
        'CG' => 'CG - Republic of the Congo',
        'CI' => 'CI - Côte d\'Ivoire',
        'CM' => 'CM - Cameroon',
        'CV' => 'CV - Cape Verde',
        'DJ' => 'DJ - Djibouti',
        'DZ' => 'DZ - Algeria',
        'EG' => 'EG - Egypt',
        'ER' => 'ER - Eritrea',
        'ET' => 'ET - Ethiopia',
        'GA' => 'GA - Gabon',
        'GH' => 'GH - Ghana',
        'GM' => 'GM - Gambia',
        'GN' => 'GN - Guinea',
        'GQ' => 'GQ - Equatorial Guinea',
        'GW' => 'GW - Guinea-Bissau',
        'KE' => 'KE - Kenya',
        'KM' => 'KM - Comoros',
        'LR' => 'LR - Liberia',
        'LS' => 'LS - Lesotho',
        'LY' => 'LY - Libya',
        'MA' => 'MA - Morocco',
        'MG' => 'MG - Madagascar',
        'ML' => 'ML - Mali',
        'MR' => 'MR - Mauritania',
        'MU' => 'MU - Mauritius',
        'MW' => 'MW - Malawi',
        'MZ' => 'MZ - Mozambique',
        'NA' => 'NA - Namibia',
        'NE' => 'NE - Niger',
        'NG' => 'NG - Nigeria',
        'RW' => 'RW - Rwanda',
        'SC' => 'SC - Seychelles',
        'SD' => 'SD - Sudan',
        'SL' => 'SL - Sierra Leone',
        'SN' => 'SN - Senegal',
        'SO' => 'SO - Somalia',
        'SS' => 'SS - South Sudan',
        'ST' => 'ST - São Tomé and Príncipe',
        'SZ' => 'SZ - Eswatini',
        'TD' => 'TD - Chad',
        'TG' => 'TG - Togo',
        'TN' => 'TN - Tunisia',
        'TZ' => 'TZ - Tanzania',
        'UG' => 'UG - Uganda',
        'ZA' => 'ZA - South Africa',
        'ZM' => 'ZM - Zambia',
        'ZW' => 'ZW - Zimbabwe',

        // Oceania
        'AU' => 'AU - Australia',
        'FJ' => 'FJ - Fiji',
        'FM' => 'FM - Micronesia',
        'GU' => 'GU - Guam',
        'KI' => 'KI - Kiribati',
        'MH' => 'MH - Marshall Islands',
        'MP' => 'MP - Northern Mariana Islands',
        'NC' => 'NC - New Caledonia',
        'NR' => 'NR - Nauru',
        'NZ' => 'NZ - New Zealand',
        'PF' => 'PF - French Polynesia',
        'PG' => 'PG - Papua New Guinea',
        'PW' => 'PW - Palau',
        'SB' => 'SB - Solomon Islands',
        'TO' => 'TO - Tonga',
        'TV' => 'TV - Tuvalu',
        'VU' => 'VU - Vanuatu',
        'WS' => 'WS - Samoa',

        // Online / Global
        'ONLINE' => 'Online / Global',
    );

    // ── Language choices (ISO 639-1 alpha-2) ─────────────────────────────────
    $language_choices = array(
        'ar' => 'Arabic',
        'da' => 'Danish',
        'de' => 'German',
        'en' => 'English',
        'es' => 'Spanish',
        'fi' => 'Finnish',
        'fr' => 'French',
        'hi' => 'Hindi',
        'it' => 'Italian',
        'ja' => 'Japanese',
        'ko' => 'Korean',
        'nl' => 'Dutch',
        'no' => 'Norwegian',
        'pl' => 'Polish',
        'pt' => 'Portuguese',
        'sv' => 'Swedish',
        'tr' => 'Turkish',
        'zh' => 'Chinese',
        'other' => 'Other',
    );

    acf_add_local_field_group( array(
        'key'                   => 'group_sfse_main',
        'title'                 => 'Event Details',
        'fields'                => array(

            // ── Tab: Core Info ────────────────────────────────────────────────
            array(
                'key'   => 'field_sfse_tab_core',
                'label' => 'Core Info',
                'type'  => 'tab',
            ),
            array(
                'key'          => 'field_sfse_organiser',
                'label'        => 'Organiser',
                'name'         => 'sfse_organiser',
                'type'         => 'text',
                'instructions' => 'Organisation or person running the event.',
                'required'     => 0,
            ),
            array(
                'key'          => 'field_sfse_event_type',
                'label'        => 'Event Type',
                'name'         => 'sfse_event_type',
                'type'         => 'select',
                'instructions' => 'Select the type of event.',
                'required'     => 0,
                'choices'      => array(
                    'conference'      => 'Conference',
                    'festival'        => 'Festival',
                    'workshop'        => 'Workshop',
                    'webinar'         => 'Webinar',
                    'summit'          => 'Summit',
                    'community_event' => 'Community Event',
                    'other'           => 'Other',
                ),
                'allow_null'   => 1,
                'ui'           => 1,
            ),
            array(
                'key'          => 'field_sfse_topics',
                'label'        => 'Topics',
                'name'         => 'sfse_topics',
                'type'         => 'checkbox',
                'instructions' => 'Select all topics that apply.',
                'required'     => 0,
                'choices'      => array(
                    'agroecology'          => 'Agroecology',
                    'food_sovereignty'     => 'Food Sovereignty',
                    'circular_economy'     => 'Circular Economy',
                    'regenerative_agri'    => 'Regenerative Agriculture',
                    'food_policy'          => 'Food Policy',
                    'nutrition'            => 'Nutrition',
                    'consumer_behaviour'   => 'Consumer Behaviour',
                    'other'                => 'Other',
                ),
                'layout'       => 'horizontal',
            ),
            array(
                'key'          => 'field_sfse_event_languages',
                'label'        => 'Event Language(s)',
                'name'         => 'sfse_event_languages',
                'type'         => 'checkbox',
                'instructions' => 'Languages in which the event is held. Select all that apply.',
                'required'     => 0,
                'choices'      => $language_choices,
                'layout'       => 'horizontal',
            ),
            array(
                'key'          => 'field_sfse_language',
                'label'        => 'Source Language',
                'name'         => 'sfse_language',
                'type'         => 'select',
                'instructions' => 'Primary language of the source website where this event was found.',
                'required'     => 0,
                'choices'      => $language_choices,
                'allow_null'   => 1,
                'ui'           => 1,
            ),
            array(
                'key'          => 'field_sfse_description',
                'label'        => 'Description',
                'name'         => 'sfse_description',
                'type'         => 'textarea',
                'instructions' => '2-3 sentences describing the event, in the original language of the source.',
                'required'     => 0,
                'rows'         => 4,
            ),

            // ── Tab: Dates ────────────────────────────────────────────────────
            array(
                'key'   => 'field_sfse_tab_dates',
                'label' => 'Dates',
                'type'  => 'tab',
            ),
            array(
                'key'            => 'field_sfse_date_start',
                'label'          => 'Start Date & Time',
                'name'           => 'sfse_date_start',
                'type'           => 'date_time_picker',
                'instructions'   => 'Event start. Defaults to 00:00 if time unknown.',
                'required'       => 1,
                'display_format' => 'd/m/Y H:i',
                'return_format'  => 'Y-m-d H:i',
                'first_day'      => 1,
            ),
            array(
                'key'            => 'field_sfse_date_end',
                'label'          => 'End Date & Time',
                'name'           => 'sfse_date_end',
                'type'           => 'date_time_picker',
                'instructions'   => 'Event end. Defaults to 23:59 if time unknown.',
                'required'       => 0,
                'display_format' => 'd/m/Y H:i',
                'return_format'  => 'Y-m-d H:i',
                'first_day'      => 1,
            ),
            array(
                'key'            => 'field_sfse_registration_deadline',
                'label'          => 'Registration Deadline',
                'name'           => 'sfse_registration_deadline',
                'type'           => 'date_time_picker',
                'instructions'   => 'Deadline to register. Defaults to 23:59 if time unknown.',
                'required'       => 0,
                'display_format' => 'd/m/Y H:i',
                'return_format'  => 'Y-m-d H:i',
                'first_day'      => 1,
            ),

            // ── Tab: Location ─────────────────────────────────────────────────
            array(
                'key'   => 'field_sfse_tab_location',
                'label' => 'Location',
                'type'  => 'tab',
            ),
            array(
                'key'          => 'field_sfse_format',
                'label'        => 'Format',
                'name'         => 'sfse_format',
                'type'         => 'select',
                'instructions' => 'How the event is held.',
                'required'     => 1,
                'choices'      => array(
                    'in-person' => 'In-Person',
                    'online'    => 'Online',
                    'hybrid'    => 'Hybrid',
                ),
                'allow_null'   => 0,
                'ui'           => 1,
            ),
            array(
                'key'          => 'field_sfse_location_name',
                'label'        => 'Location Name',
                'name'         => 'sfse_location_name',
                'type'         => 'text',
                'instructions' => 'Name of the venue or platform where the event takes place.',
                'required'     => 0,
            ),
            array(
                'key'          => 'field_sfse_city',
                'label'        => 'City',
                'name'         => 'sfse_city',
                'type'         => 'text',
                'required'     => 0,
            ),
            array(
                'key'          => 'field_sfse_country',
                'label'        => 'Country',
                'name'         => 'sfse_country',
                'type'         => 'select',
                'instructions' => 'ISO 3166-1 alpha-2 country code.',
                'required'     => 0,
                'choices'      => $country_choices,
                'allow_null'   => 1,
                'ui'           => 1,
                'ajax'         => 1,
            ),
            array(
                'key'          => 'field_sfse_continent',
                'label'        => 'Continent',
                'name'         => 'sfse_continent',
                'type'         => 'select',
                'required'     => 0,
                'choices'      => array(
                    'Africa'        => 'Africa',
                    'Asia'          => 'Asia',
                    'Europe'        => 'Europe',
                    'North America' => 'North America',
                    'Oceania'       => 'Oceania',
                    'Online'        => 'Online',
                    'South America' => 'South America',
                ),
                'allow_null'   => 1,
                'ui'           => 1,
            ),

            // ── Tab: Cost & Links ─────────────────────────────────────────────
            array(
                'key'   => 'field_sfse_tab_links',
                'label' => 'Cost & Links',
                'type'  => 'tab',
            ),
            array(
                'key'          => 'field_sfse_cost',
                'label'        => 'Cost',
                'name'         => 'sfse_cost',
                'type'         => 'text',
                'instructions' => 'e.g. Free, €50, Paid – see link',
                'required'     => 0,
            ),
            array(
                'key'          => 'field_sfse_event_link',
                'label'        => 'Event Link',
                'name'         => 'sfse_event_link',
                'type'         => 'url',
                'instructions' => 'Direct URL to the event page.',
                'required'     => 0,
            ),
            array(
                'key'          => 'field_sfse_source_url',
                'label'        => 'Source URL',
                'name'         => 'sfse_source_url',
                'type'         => 'url',
                'instructions' => 'URL where the agent discovered this event.',
                'required'     => 0,
            ),
            array(
                'key'          => 'field_sfse_image_url',
                'label'        => 'Banner Image URL',
                'name'         => 'sfse_image_url',
                'type'         => 'url',
                'instructions' => 'URL of the event\'s og:image promotional banner (set automatically by the agent). Displayed with attribution. Leave blank to show placeholder.',
                'required'     => 0,
            ),

            // ── Tab: Quality Control ──────────────────────────────────────────
            array(
                'key'   => 'field_sfse_tab_qc',
                'label' => 'Quality Control',
                'type'  => 'tab',
            ),
            array(
                'key'          => 'field_sfse_verified',
                'label'        => 'Verified',
                'name'         => 'sfse_verified',
                'type'         => 'true_false',
                'instructions' => 'Check once you have reviewed and approved this event.',
                'required'     => 0,
                'default_value'=> 0,
                'ui'           => 1,
                'ui_on_text'   => 'Verified',
                'ui_off_text'  => 'Unverified',
            ),
            array(
                'key'          => 'field_sfse_rejection_reason',
                'label'        => 'Rejection Reason',
                'name'         => 'sfse_rejection_reason',
                'type'         => 'select',
                'instructions' => 'If rejecting this event, select the reason. Used as agent feedback.',
                'required'     => 0,
                'choices'      => array(
                    'not_relevant'     => 'Not relevant',
                    'wrong_language'   => 'Wrong language',
                    'duplicate'        => 'Duplicate',
                    'poor_data'        => 'Poor data quality',
                    'past_event'       => 'Past event',
                ),
                'allow_null'   => 1,
                'ui'           => 1,
            ),
            array(
                'key'          => 'field_sfse_duplicate_of',
                'label'        => 'Duplicate Of',
                'name'         => 'sfse_duplicate_of',
                'type'         => 'post_object',
                'instructions' => 'If this is a duplicate, reference the original event here.',
                'required'     => 0,
                'post_type'    => array( 'sfse_event' ),
                'allow_null'   => 1,
                'return_format'=> 'id',
                'ui'           => 1,
            ),

            // ── Tab: Agent Info ───────────────────────────────────────────────
            array(
                'key'   => 'field_sfse_tab_agent',
                'label' => 'Agent Info',
                'type'  => 'tab',
            ),
            array(
                'key'            => 'field_sfse_date_added',
                'label'          => 'Date Added',
                'name'           => 'sfse_date_added',
                'type'           => 'date_time_picker',
                'instructions'   => 'Automatically set by the agent when first published.',
                'required'       => 0,
                'display_format' => 'd/m/Y H:i',
                'return_format'  => 'Y-m-d H:i',
                'first_day'      => 1,
                'readonly'       => 1,
            ),
            array(
                'key'            => 'field_sfse_last_updated',
                'label'          => 'Last Updated',
                'name'           => 'sfse_last_updated',
                'type'           => 'date_time_picker',
                'instructions'   => 'Automatically set by the agent when a change is detected.',
                'required'       => 0,
                'display_format' => 'd/m/Y H:i',
                'return_format'  => 'Y-m-d H:i',
                'first_day'      => 1,
                'readonly'       => 1,
            ),

        ), // end fields

        'location' => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'sfse_event',
                ),
            ),
        ),

        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => 'All fields for the Sustainable Food System Events CPT.',
    ) );
}
add_action( 'acf/init', 'sfse_register_acf_fields' );
